#!/bin/bash

cd /Volumes/QuantOsUSB

echo "+++++++++++进入 venv 容器+++++++"
source /Volumes/QuantOsUSB/QuantOsUSB//hikyuu/Contents/Resources/venv/bin/activate

echo " ^^^^^^^^^显示 rqalpha mod 模块开启状态^^^^^^^^"
#rqalpha mod list

echo "VVV开始更新最新 rqalpha 数据-可以用 Control+C 停止更新！！！VVV"
#rqalpha update-bundle

echo "^^^^^^^^^^开启 notebook 并启动浏览器，用 Control+C 退出！！^^^^^^^^^"
jupyter notebook

echo "^^^^^^^^ notebook 退出，开启 jupyterlab 浏览器，用 Control+C 退出！！^^^^^^^^"

#jupyter lab

echo "^^^^^^^^ jupyterlab 退出，退出 venv 容器^^^^^^^^^^"

deactivate
echo "+++++++++++成功退出+++++++++还原默认+++++++"
