#!/bin/bash

cd /Volumes/QuantOsUSB

echo "+++++++++++进入 venv 容器+++++++"
source /Volumes/QuantOsUSB/QuantOsUSB/quantaxis/Contents/Resources/venv/bin/activate

echo "后台开启 mongodb 服务，数据目录在/Volumes/QuantOsUSB/data/mongodb/data/db"

jupyter notebook

echo "VVV回车开启 quantaxis 输入：save all 更新数据，可以用 exit 退出！！！VVV"

echo "^^^^^^^^^^开启 notebook 并启动浏览器，用 Control+C 退出！！^^^^^^^^^"

echo "^^^^^^^^ notebook 退出，开启 jupyterlab 浏览器，用 Control+C 退出！！^^^^^^^^"

echo "^^^^^^^^ mongodb 退出，退出 venv 容器^^^^^^^^^^"
deactivate

echo "+++++++++++成功退出+++++++++还原默认+++++++"
